import { ChurchSermon } from '../../types';

/**
 * Dataset demonstrativo inicial de sermões e mensagens da igreja.
 * Consome estritamente o contrato canônico ChurchSermon definido em src/types/index.ts.
 * Tenant proprietário: 'ib_central'
 */
export const INITIAL_DEMO_SERMONS: ChurchSermon[] = [
  {
    id: 'sermon_01',
    tenantId: 'ib_central',
    title: 'A Certeza da Esperança em Dias Incertos',
    slug: 'a-certeza-da-esperanca-em-dias-incertos',
    description:
      'Uma reflexão profunda sobre como a soberania de Deus nos ancora durante as tempestades da vida. Aprendemos em Romanos que todas as coisas cooperam para o bem daqueles que amam a Deus.',
    preacher: 'Pr. Roberto Silveira',
    date: '2026-09-06',
    scriptureReference: 'Romanos 8:28-39',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-esperanca',
    audioMediaId: 'med_11',
    thumbnailMediaId: 'med_02',
    status: 'published',
    createdAt: '2026-09-06T19:00:00Z',
    updatedAt: '2026-09-06T21:30:00Z',
  },
  {
    id: 'sermon_02',
    tenantId: 'ib_central',
    title: 'Vivendo pela Fé e Não pelo que Vemos',
    slug: 'vivendo-pela-fe-e-nao-pelo-que-vemos',
    description:
      'Mensagem inspiradora sobre a natureza transformadora da fé bíblica. Como confiar na fidelidade divina quando os cenários ao nosso redor parecem desafiadores.',
    preacher: 'Pra. Helena Albuquerque',
    date: '2026-08-30',
    scriptureReference: 'Hebreus 11:1-6',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-fe',
    audioMediaId: 'med_11',
    thumbnailMediaId: 'med_05',
    status: 'published',
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-08-30T12:15:00Z',
  },
  {
    id: 'sermon_03',
    tenantId: 'ib_central',
    title: 'O Bom Pastor e o Cuidado com o Rebanho',
    slug: 'o-bom-pastor-e-o-cuidado-com-o-rebanho',
    description:
      'Estudo expositivo do Salmo 23 abordando o descanso na presença do Senhor, a direção em veredas de justiça e o consolo nas horas mais difíceis.',
    preacher: 'Pr. Carlos Eduardo',
    date: '2026-08-23',
    scriptureReference: 'Salmos 23:1-6',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-salmo23',
    thumbnailMediaId: 'med_03',
    status: 'published',
    createdAt: '2026-08-23T19:00:00Z',
    updatedAt: '2026-08-23T21:00:00Z',
  },
  {
    id: 'sermon_04',
    tenantId: 'ib_central',
    title: 'Vencendo a Ansiedade com Oração e Gratidão',
    slug: 'vencendo-a-ansiedade-com-oracao-e-gratidao',
    description:
      'Instruções práticas e bíblicas para lidar com as pressões do cotidiano, apresentando nossos anseios a Deus em oração e experimentando a paz que excede todo entendimento.',
    preacher: 'Pr. Roberto Silveira',
    date: '2026-08-16',
    scriptureReference: 'Filipenses 4:4-9',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-ansiedade',
    audioMediaId: 'med_11',
    thumbnailMediaId: 'med_07',
    status: 'published',
    createdAt: '2026-08-16T19:00:00Z',
    updatedAt: '2026-08-16T21:10:00Z',
  },
  {
    id: 'sermon_05',
    tenantId: 'ib_central',
    title: 'Permanecendo na Videira Verdadeira',
    slug: 'permanecendo-na-videira-verdadeira',
    description:
      'A dependência vital entre o discípulo e Cristo. Como a frutificação espiritual é consequência direta da nossa comunhão diária com o Senhor.',
    preacher: 'Pr. Marcos Vinícius',
    date: '2026-08-09',
    scriptureReference: 'João 15:1-8',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-videira',
    thumbnailMediaId: 'med_01',
    status: 'published',
    createdAt: '2026-08-09T10:00:00Z',
    updatedAt: '2026-08-09T12:00:00Z',
  },
  {
    id: 'sermon_06',
    tenantId: 'ib_central',
    title: 'O Chamado à Graça e ao Discipulado Radical',
    slug: 'o-chamado-a-graca-e-ao-discipulado-radical',
    description:
      'O que significa carregar a cruz diariamente e seguir a Jesus com integridade e amor sacrificial na sociedade contemporânea.',
    preacher: 'Pra. Helena Albuquerque',
    date: '2026-09-13',
    scriptureReference: 'Lucas 9:23-26',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-discipulado',
    thumbnailMediaId: 'med_05',
    status: 'draft',
    createdAt: '2026-09-04T15:30:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
  },
  {
    id: 'sermon_07',
    tenantId: 'ib_central',
    title: 'Princípios Bíblicos de Mordomia e Finanças Cristãs',
    slug: 'principios-biblicos-de-mordomia-e-financas-cristas',
    description:
      'Estudo especial sobre planejamento, generosidade cristã e contentamento conforme as Escrituras sagradas.',
    preacher: 'Pr. Carlos Eduardo',
    date: '2026-09-20',
    scriptureReference: '1 Timóteo 6:6-10',
    status: 'draft',
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T11:45:00Z',
  },
  {
    id: 'sermon_08',
    tenantId: 'ib_central',
    title: 'Série Renovados: A Importância da Mente em Cristo (Parte 1)',
    slug: 'serie-renovados-a-importancia-da-mente-em-cristo-parte-1',
    description:
      'Primeiro sermão da série especial Renovados ministrada no início do ano. Transformação de caráter pelo renovar do nosso entendimento.',
    preacher: 'Pr. Roberto Silveira',
    date: '2026-01-18',
    scriptureReference: 'Romanos 12:1-2',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-renovados-01',
    audioMediaId: 'med_11',
    thumbnailMediaId: 'med_02',
    status: 'archived',
    createdAt: '2026-01-18T19:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'sermon_09',
    tenantId: 'ib_central',
    title: 'Culto de Vigília de Ano Novo: Firmes na Promessa',
    slug: 'culto-de-vigilia-de-ano-novo-firmes-na-promessa',
    description:
      'Mensagem profética e pastoral ministrada na transição de ano, fortalecendo a igreja para os propósitos de Deus no ano vindouro.',
    preacher: 'Pr. Roberto Silveira',
    date: '2025-12-31',
    scriptureReference: 'Josué 1:1-9',
    videoUrl: 'https://www.youtube.com/watch?v=exemplo-sermon-vigilia-2025',
    thumbnailMediaId: 'med_01',
    status: 'archived',
    createdAt: '2025-12-31T23:00:00Z',
    updatedAt: '2026-02-10T14:20:00Z',
  },
];
