import { Page } from '../../types';

export const INITIAL_DEMO_PAGES: Page[] = [
  {
    id: 'page_home',
    tenantId: 'ib_central',
    title: 'Página Inicial',
    slug: '/',
    status: 'published',
    order: 1,
    isHome: true,
    publishedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: 'Hoje, às 08:30',
    seo: {
      metaTitle: 'Igreja Batista Central — Comunhão, Adoração e Missão',
      metaDescription: 'Bem-vindo à Igreja Batista Central. Cultos todos os domingos às 10h e 18h. Venha adorar a Deus conosco!',
      keywords: ['igreja batista', 'cultos', 'são paulo', 'comunhão', 'família'],
    },
    sections: [
      {
        id: 'sec_hero',
        title: 'Banner Principal (Hero)',
        order: 1,
        isVisible: true,
        blocks: [
          {
            id: 'blk_hero_1',
            type: 'hero',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'full', alignment: 'center' },
            data: { title: 'Uma Igreja Viva para Todas as Famílias' },
          },
        ],
      },
      {
        id: 'sec_schedule',
        title: 'Cultos & Horários',
        order: 2,
        isVisible: true,
        blocks: [
          {
            id: 'blk_schedule_1',
            type: 'schedule',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'standard' },
            data: {},
          },
        ],
      },
      {
        id: 'sec_pastoral',
        title: 'Mensagem Pastoral',
        order: 3,
        isVisible: true,
        blocks: [
          {
            id: 'blk_about_1',
            type: 'about',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'standard' },
            data: {},
          },
        ],
      },
      {
        id: 'sec_events',
        title: 'Próximos Eventos',
        order: 4,
        isVisible: true,
        blocks: [
          {
            id: 'blk_events_1',
            type: 'events',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'standard' },
            data: {},
          },
        ],
      },
      {
        id: 'sec_sermons',
        title: 'Últimos Sermões',
        order: 5,
        isVisible: true,
        blocks: [
          {
            id: 'blk_sermons_1',
            type: 'sermons',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'standard' },
            data: {},
          },
        ],
      },
      {
        id: 'sec_contact',
        title: 'Localização & Contato',
        order: 6,
        isVisible: true,
        blocks: [
          {
            id: 'blk_contact_1',
            type: 'contact',
            order: 1,
            isVisible: true,
            config: { containerWidth: 'standard' },
            data: {},
          },
        ],
      },
    ],
  },
  {
    id: 'page_about',
    tenantId: 'ib_central',
    title: 'Quem Somos',
    slug: '/quem-somos',
    status: 'published',
    order: 2,
    isHome: false,
    publishedAt: '2026-09-02T14:00:00Z',
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: 'Ontem, às 14:20',
    seo: {
      metaTitle: 'Quem Somos — História e Liderança da Igreja Batista Central',
      metaDescription: 'Conheça nossa história, corpo pastoral, visão, valores e declaração doutrinária.',
      keywords: ['história', 'pastores', 'doutrina', 'visão'],
    },
    sections: [
      {
        id: 'sec_about_hist',
        title: 'Nossa História',
        order: 1,
        isVisible: true,
        blocks: [],
      },
      {
        id: 'sec_about_pastors',
        title: 'Corpo Pastoral',
        order: 2,
        isVisible: true,
        blocks: [],
      },
      {
        id: 'sec_about_values',
        title: 'Visão e Valores',
        order: 3,
        isVisible: true,
        blocks: [],
      },
      {
        id: 'sec_about_faith',
        title: 'Declaração de Fé',
        order: 4,
        isVisible: true,
        blocks: [],
      },
    ],
  },
  {
    id: 'page_schedule',
    tenantId: 'ib_central',
    title: 'Cultos e Horários',
    slug: '/cultos',
    status: 'published',
    order: 3,
    isHome: false,
    publishedAt: '2026-09-02T16:00:00Z',
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: 'Há 3 dias',
    seo: {
      metaTitle: 'Horários dos Cultos e Reuniões — Igreja Batista Central',
      metaDescription: 'Confira nossos horários semanais de celebração, escola bíblica e reuniões de oração.',
    },
    sections: [
      { id: 'sec_sched_main', title: 'Cultos Dominicais', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_sched_week', title: 'Reuniões Semanais', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_sched_location', title: 'Como Chegar', order: 3, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_ministries',
    tenantId: 'ib_central',
    title: 'Ministérios',
    slug: '/ministerios',
    status: 'published',
    order: 4,
    isHome: false,
    publishedAt: '2026-09-03T11:00:00Z',
    createdAt: '2026-08-17T09:00:00Z',
    updatedAt: 'Há 5 dias',
    seo: {
      metaTitle: 'Ministérios e Departamentos — Igreja Batista Central',
      metaDescription: 'Conheça nossos grupos de conexão: Infantil, Jovens, Casais, Ação Social e Louvor.',
    },
    sections: [
      { id: 'sec_min_intro', title: 'Visão Ministerial', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_min_kids', title: 'Ministério Infantil', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_min_youth', title: 'Juventude Conectada', order: 3, isVisible: true, blocks: [] },
      { id: 'sec_min_families', title: 'Famílias Fortes', order: 4, isVisible: true, blocks: [] },
      { id: 'sec_min_action', title: 'Ação Social Eclesial', order: 5, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_sermons',
    tenantId: 'ib_central',
    title: 'Sermões e Mensagens',
    slug: '/sermoes',
    status: 'published',
    order: 5,
    isHome: false,
    publishedAt: '2026-09-04T09:30:00Z',
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: 'Há 6 dias',
    seo: {
      metaTitle: 'Acervo de Sermões e Mensagens Bíblicas',
      metaDescription: 'Assista e ouça as mensagens ministradas nos cultos de celebração.',
    },
    sections: [
      { id: 'sec_sermon_featured', title: 'Mensagem em Destaque', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_sermon_series', title: 'Séries Recentes', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_sermon_podcasts', title: 'Podcasts e Áudios', order: 3, isVisible: true, blocks: [] },
      { id: 'sec_sermon_youtube', title: 'Canal Oficial YouTube', order: 4, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_events',
    tenantId: 'ib_central',
    title: 'Eventos e Agenda',
    slug: '/eventos',
    status: 'published',
    order: 6,
    isHome: false,
    publishedAt: '2026-09-04T12:00:00Z',
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: 'Há 1 semana',
    seo: {
      metaTitle: 'Calendário de Eventos e Conferências',
      metaDescription: 'Participe dos próximos eventos, congressos e encontros da nossa igreja.',
    },
    sections: [
      { id: 'sec_ev_calendar', title: 'Calendário Mensal', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_ev_conf', title: 'Conferência Anual 2026', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_ev_register', title: 'Inscrições Online', order: 3, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_prayer',
    tenantId: 'ib_central',
    title: 'Pedidos de Oração',
    slug: '/oracao',
    status: 'draft',
    order: 7,
    isHome: false,
    createdAt: '2026-09-05T15:00:00Z',
    updatedAt: 'Ontem, às 17:10',
    seo: {
      metaTitle: 'Envie seu Pedido de Oração — Igreja Batista Central',
      metaDescription: 'Nossa equipe pastoral e de intercessão orará pelas suas causas com total confidencialidade.',
    },
    sections: [
      { id: 'sec_pray_form', title: 'Formulário de Intercessão', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_pray_team', title: 'Equipe de Oração', order: 2, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_news',
    tenantId: 'ib_central',
    title: 'Notícias e Boletins',
    slug: '/noticias',
    status: 'published',
    order: 8,
    isHome: false,
    publishedAt: '2026-09-05T18:00:00Z',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: 'Há 2 semanas',
    seo: {
      metaTitle: 'Notícias, Comunicados e Artigos Pastorais',
      metaDescription: 'Fique por dentro de tudo o que acontece na vida e ministério da nossa igreja.',
    },
    sections: [
      { id: 'sec_news_lead', title: 'Notícia em Destaque', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_news_list', title: 'Feed de Artigos', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_news_archive', title: 'Boletins Semanais', order: 3, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_giving',
    tenantId: 'ib_central',
    title: 'Dízimos e Ofertas',
    slug: '/contribuir',
    status: 'published',
    order: 9,
    isHome: false,
    publishedAt: '2026-09-05T19:00:00Z',
    createdAt: '2026-08-21T10:00:00Z',
    updatedAt: 'Há 3 semanas',
    seo: {
      metaTitle: 'Contribuições, Dízimos e Ofertas — Igreja Batista Central',
      metaDescription: 'Apoie a obra e os projetos sociais da igreja através de transferências e PIX.',
    },
    sections: [
      { id: 'sec_give_word', title: 'Princípio da Generosidade', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_give_pix', title: 'Chave PIX e Contas Bancárias', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_give_projects', title: 'Projetos Missionários Apoiados', order: 3, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_contact',
    tenantId: 'ib_central',
    title: 'Fale Conosco',
    slug: '/contato',
    status: 'published',
    order: 10,
    isHome: false,
    publishedAt: '2026-09-06T10:00:00Z',
    createdAt: '2026-08-22T08:00:00Z',
    updatedAt: 'Há 1 mês',
    seo: {
      metaTitle: 'Fale Conosco — Contatos e Localização',
      metaDescription: 'Entre em contato com nossa secretaria ou visite nosso templo em São Paulo.',
    },
    sections: [
      { id: 'sec_contact_channels', title: 'Canais de Atendimento', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_contact_map', title: 'Mapa e Transporte', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_contact_form', title: 'Envie uma Mensagem', order: 3, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_missions_archived',
    tenantId: 'ib_central',
    title: 'Campanha de Missões 2025',
    slug: '/missoes-2025',
    status: 'archived',
    order: 11,
    isHome: false,
    createdAt: '2025-05-10T10:00:00Z',
    updatedAt: 'Há 3 meses',
    seo: {
      metaTitle: 'Campanha de Missões 2025 — Relatório de Atividades',
      metaDescription: 'Relatório das atividades missionárias desenvolvidas em 2025.',
      noIndex: true,
    },
    sections: [
      { id: 'sec_miss_rep', title: 'Relatório Geral', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_miss_photos', title: 'Galeria de Fotos', order: 2, isVisible: true, blocks: [] },
      { id: 'sec_miss_thanks', title: 'Agradecimento à Igreja', order: 3, isVisible: true, blocks: [] },
      { id: 'sec_miss_closed', title: 'Campanha Encerrada', order: 4, isVisible: true, blocks: [] },
    ],
  },
  {
    id: 'page_retreat_draft',
    tenantId: 'ib_central',
    title: 'Retiro Espiritual de Carnaval 2027',
    slug: '/retiro-2027',
    status: 'draft',
    order: 12,
    isHome: false,
    createdAt: '2026-09-06T14:30:00Z',
    updatedAt: 'Há 4 dias',
    seo: {
      metaTitle: 'Retiro Espiritual 2027 — Inscrições e Hospedagem',
      metaDescription: 'Informações sobre valores, hospedagem e inscrições para o retiro espiritual.',
    },
    sections: [
      { id: 'sec_ret_intro', title: 'Tema e Preletores', order: 1, isVisible: true, blocks: [] },
      { id: 'sec_ret_form', title: 'Ficha de Inscrição', order: 2, isVisible: true, blocks: [] },
    ],
  },
];
