import { ChurchGalleryAlbum } from '../../types';

/**
 * Dataset demonstrativo inicial de álbuns de fotos da congregação.
 * Utiliza estritamente os campos canônicos de ChurchGalleryAlbum.
 * Todos os dados são 100% fictícios para demonstração em memória.
 */
export const INITIAL_DEMO_GALLERY: ChurchGalleryAlbum[] = [
  {
    id: 'alb_01',
    tenantId: 'ib_central',
    title: 'Batismo nas Águas - Celebração de Primavera',
    slug: 'batismo-aguas-primavera-2026',
    description: 'Registro solene e emocionante do batismo comunitário de novos irmãos na fé em Cristo.',
    coverMediaId: 'med_04',
    mediaIds: ['med_04', 'med_02', 'med_01', 'med_05'],
    status: 'active',
    createdAt: '2026-08-28T17:00:00Z',
    updatedAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'alb_02',
    tenantId: 'ib_central',
    title: 'Culto Especial de Celebração e Gratidão',
    slug: 'culto-especial-celebracao-gratidao',
    description: 'Noite de comunhão, adoração fervorosa e ministração da Palavra de Deus no templo sede.',
    coverMediaId: 'med_02',
    mediaIds: ['med_02', 'med_01', 'med_03', 'med_05'],
    status: 'active',
    createdAt: '2026-08-20T21:30:00Z',
    updatedAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'alb_03',
    tenantId: 'ib_central',
    title: 'Escola Bíblica de Férias e Ministério Infantil',
    slug: 'escola-biblica-ferias-kids-2026',
    description: 'Momentos de aprendizado bíblico, dinâmicas e oficinas pedagógicas com as crianças.',
    coverMediaId: 'med_06',
    mediaIds: ['med_06', 'med_05', 'med_01'],
    status: 'active',
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-08-19T14:20:00Z',
  },
  {
    id: 'alb_04',
    tenantId: 'ib_central',
    title: 'Fachada e Instalações do Templo Central',
    slug: 'fachada-instalacoes-templo-central',
    description: 'Registros fotográficos da arquitetura exterior, naves e dependências da congregação.',
    coverMediaId: 'med_01',
    mediaIds: ['med_01', 'med_02', 'med_05'],
    status: 'active',
    createdAt: '2026-08-15T15:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'alb_05',
    tenantId: 'ib_central',
    title: 'Conferência Anual da Liderança Pastoral',
    slug: 'conferencia-anual-lideranca-pastoral',
    description: 'Encontro de pastores, presbíteros e diáconos para alinhamento da visão ministerial e oração.',
    coverMediaId: 'med_03',
    mediaIds: ['med_03', 'med_05', 'med_02'],
    status: 'active',
    createdAt: '2026-08-10T12:00:00Z',
    updatedAt: '2026-08-11T18:45:00Z',
  },
  {
    id: 'alb_06',
    tenantId: 'ib_central',
    title: 'Cantata de Natal e Vigília de Encerramento 2025',
    slug: 'cantata-natal-vigilia-2025',
    description: 'Apresentação coral festiva e momentos de oração de encerramento do ano congregacional.',
    coverMediaId: 'med_02',
    mediaIds: ['med_02', 'med_05', 'med_01'],
    status: 'archived',
    createdAt: '2025-12-31T23:50:00Z',
    updatedAt: '2026-01-05T10:00:00Z',
  },
  {
    id: 'alb_07',
    tenantId: 'ib_central',
    title: 'Ação Social e Apoio Comunitário de Inverno',
    slug: 'acao-social-apoio-comunitario-inverno',
    description: 'Distribuição de cestas de alimentos, agasalhos e atendimento pastoral voluntário.',
    coverMediaId: 'med_06',
    mediaIds: ['med_06', 'med_01', 'med_04'],
    status: 'archived',
    createdAt: '2026-07-12T17:30:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
  },
];
