import { FormDefinition } from '../../types';

export const INITIAL_DEMO_FORMS: FormDefinition[] = [
  {
    id: 'form_prayer_request',
    tenantId: 'tenant_batista_central',
    name: 'Pedido de Oração',
    slug: 'pedido-de-oracao',
    description:
      'Canal de intercessão da igreja. Nossos pastores e intercessores oram diariamente pelos pedidos recebidos.',
    status: 'active',
    fields: [
      {
        id: 'f_pr_1',
        name: 'requester_name',
        label: 'Nome Completo',
        type: 'text',
        required: true,
        placeholder: 'Informe seu nome ou digite "Anônimo"',
        order: 1,
      },
      {
        id: 'f_pr_2',
        name: 'requester_email',
        label: 'E-mail de Contato',
        type: 'email',
        required: false,
        placeholder: 'seuemail@exemplo.com',
        helpText: 'Opcional. Preencha se desejar receber acompanhamento pastoral.',
        order: 2,
      },
      {
        id: 'f_pr_3',
        name: 'requester_phone',
        label: 'Telefone / WhatsApp',
        type: 'tel',
        required: false,
        placeholder: '(11) 98765-4321',
        order: 3,
      },
      {
        id: 'f_pr_4',
        name: 'category',
        label: 'Motivo da Oração',
        type: 'select',
        required: true,
        helpText: 'Selecione a área principal da necessidade',
        options: [
          { value: 'saude', label: 'Saúde e Restauração Física' },
          { value: 'familia', label: 'Família e Casamento' },
          { value: 'espiritual', label: 'Vida Espiritual e Paz' },
          { value: 'financeiro', label: 'Emprego e Finanças' },
          { value: 'agradecimento', label: 'Agradecimento e Louvor' },
          { value: 'outros', label: 'Outro Motivo' },
        ],
        order: 4,
      },
      {
        id: 'f_pr_5',
        name: 'request_details',
        label: 'Descreva seu Pedido',
        type: 'textarea',
        required: true,
        placeholder: 'Compartilhe conosco o motivo pelo qual deseja que intercedamos...',
        order: 5,
      },
      {
        id: 'f_pr_6',
        name: 'is_confidential',
        label: 'Manter sigilo pastoral estrito',
        type: 'boolean',
        required: false,
        helpText: 'Se marcado, o pedido será compartilhado somente com a equipe pastoral.',
        order: 6,
      },
    ],
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'form_contact',
    tenantId: 'tenant_batista_central',
    name: 'Contato Geral',
    slug: 'contato',
    description:
      'Formulário geral para mensagens, dúvidas, sugestões e comunicação com a secretaria da igreja.',
    status: 'active',
    fields: [
      {
        id: 'f_ct_1',
        name: 'full_name',
        label: 'Seu Nome',
        type: 'text',
        required: true,
        placeholder: 'Como podemos te chamar?',
        order: 1,
      },
      {
        id: 'f_ct_2',
        name: 'email',
        label: 'Endereço de E-mail',
        type: 'email',
        required: true,
        placeholder: 'exemplo@dominio.com',
        order: 2,
      },
      {
        id: 'f_ct_3',
        name: 'phone',
        label: 'Telefone com DDD',
        type: 'tel',
        required: false,
        placeholder: '(11) 90000-0000',
        order: 3,
      },
      {
        id: 'f_ct_4',
        name: 'department',
        label: 'Destinatário / Departamento',
        type: 'select',
        required: true,
        options: [
          { value: 'secretaria', label: 'Secretaria da Igreja' },
          { value: 'pastoral', label: 'Gabinete Pastoral' },
          { value: 'comunicacao', label: 'Comunicação e Mídia' },
          { value: 'acao_social', label: 'Ação Social e Diaconia' },
        ],
        order: 4,
      },
      {
        id: 'f_ct_5',
        name: 'message',
        label: 'Mensagem',
        type: 'textarea',
        required: true,
        placeholder: 'Escreva sua mensagem...',
        order: 5,
      },
    ],
    createdAt: '2026-08-12T11:20:00Z',
    updatedAt: '2026-09-01T09:15:00Z',
  },
  {
    id: 'form_youth_retreat',
    tenantId: 'tenant_batista_central',
    name: 'Inscrição para Retiro de Jovens',
    slug: 'inscricao-retiro-jovens',
    description:
      'Ficha de inscrição para o Retiro Anual da Juventude Central com hospedagem e alimentação incluídas.',
    status: 'active',
    fields: [
      {
        id: 'f_yr_1',
        name: 'participant_name',
        label: 'Nome Completo do Participante',
        type: 'text',
        required: true,
        placeholder: 'Nome sem abreviações',
        order: 1,
      },
      {
        id: 'f_yr_2',
        name: 'birth_date',
        label: 'Data de Nascimento',
        type: 'date',
        required: true,
        helpText: 'Necessário para divisão das faixas etárias e quartos.',
        order: 2,
      },
      {
        id: 'f_yr_3',
        name: 'participant_email',
        label: 'E-mail do Participante',
        type: 'email',
        required: true,
        placeholder: 'jovem@exemplo.com',
        order: 3,
      },
      {
        id: 'f_yr_4',
        name: 'emergency_phone',
        label: 'Telefone de Emergência (Pais / Responsável)',
        type: 'tel',
        required: true,
        placeholder: '(11) 91111-2222',
        order: 4,
      },
      {
        id: 'f_yr_5',
        name: 'dietary_restrictions',
        label: 'Possui restrição alimentar ou alergia?',
        type: 'text',
        required: false,
        placeholder: 'Glúten, lactose, frutos do mar, etc. (se não tiver, deixe em branco)',
        order: 5,
      },
      {
        id: 'f_yr_6',
        name: 'transport_option',
        label: 'Opção de Transporte',
        type: 'radio',
        required: true,
        options: [
          { value: 'onibus_igreja', label: 'Vou no ônibus fretado da igreja' },
          { value: 'carro_proprio', label: 'Vou em transporte próprio / carona' },
        ],
        order: 6,
      },
      {
        id: 'f_yr_7',
        name: 'needs_financial_aid',
        label: 'Solicitar bolsa parcial de auxílio ao retiro',
        type: 'boolean',
        required: false,
        order: 7,
      },
    ],
    createdAt: '2026-08-15T15:00:00Z',
    updatedAt: '2026-09-04T16:45:00Z',
  },
  {
    id: 'form_volunteer',
    tenantId: 'tenant_batista_central',
    name: 'Seja Voluntário',
    slug: 'seja-voluntario',
    description:
      'Cadastro de talentos e disponibilidade para servir nos ministérios da congregação.',
    status: 'active',
    fields: [
      {
        id: 'f_vol_1',
        name: 'volunteer_name',
        label: 'Nome Completo',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        id: 'f_vol_2',
        name: 'phone',
        label: 'WhatsApp',
        type: 'tel',
        required: true,
        placeholder: '(11) 98888-7777',
        order: 2,
      },
      {
        id: 'f_vol_3',
        name: 'preferred_ministry',
        label: 'Ministério de Interesse Principal',
        type: 'select',
        required: true,
        options: [
          { value: 'louvor', label: 'Ministério de Louvor e Música' },
          { value: 'infantil', label: 'Ministério Infantil (EBD e Cultinho)' },
          { value: 'midia', label: 'Mídia, Áudio e Transmissão' },
          { value: 'recepcao', label: 'Recepção e Boas-Vindas' },
          { value: 'acao_social', label: 'Ação Social e Bazar Beneficente' },
          { value: 'intercessao', label: 'Grupo de Intercessão' },
        ],
        order: 3,
      },
      {
        id: 'f_vol_4',
        name: 'availability',
        label: 'Disponibilidade de Horários',
        type: 'radio',
        required: true,
        options: [
          { value: 'domingo_manha', label: 'Domingos pela manhã (EBD)' },
          { value: 'domingo_noite', label: 'Domingos à noite (Culto de Celebração)' },
          { value: 'quarta_noite', label: 'Quartas-feiras à noite (Culto de Oração)' },
          { value: 'sabado', label: 'Sábados (Eventos e Ensaios)' },
        ],
        order: 4,
      },
      {
        id: 'f_vol_5',
        name: 'experience_notes',
        label: 'Conte um pouco sobre suas habilidades e experiências',
        type: 'textarea',
        required: false,
        placeholder: 'Ex: Toco violão, tenho experiência com crianças, formação em pedagogia...',
        order: 5,
      },
    ],
    createdAt: '2026-08-20T14:10:00Z',
    updatedAt: '2026-09-03T18:00:00Z',
  },
  {
    id: 'form_pastoral_visit',
    tenantId: 'tenant_batista_central',
    name: 'Pedido de Visita Pastoral',
    slug: 'visita-pastoral',
    description:
      'Solicitação para visita pastoral em domicílio, hospital ou acolhimento individual.',
    status: 'draft',
    fields: [
      {
        id: 'f_pv_1',
        name: 'requester_name',
        label: 'Nome de quem solicita ou receberá a visita',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        id: 'f_pv_2',
        name: 'phone',
        label: 'Telefone para confirmação',
        type: 'tel',
        required: true,
        order: 2,
      },
      {
        id: 'f_pv_3',
        name: 'address_location',
        label: 'Endereço Completo ou Hospital / Quarto',
        type: 'text',
        required: true,
        placeholder: 'Rua, número, bairro ou Hospital / Ala / Quarto',
        order: 3,
      },
      {
        id: 'f_pv_4',
        name: 'visit_type',
        label: 'Tipo de Visita',
        type: 'radio',
        required: true,
        options: [
          { value: 'domicilio', label: 'Visita Residencial / Domiciliar' },
          { value: 'hospital', label: 'Visita Hospitalar' },
          { value: 'gabinete', label: 'Atendimento no Gabinete Pastoral' },
        ],
        order: 4,
      },
      {
        id: 'f_pv_5',
        name: 'preferred_date',
        label: 'Data de Preferência',
        type: 'date',
        required: false,
        order: 5,
      },
      {
        id: 'f_pv_6',
        name: 'details',
        label: 'Informações Adicionais para o Pastor',
        type: 'textarea',
        required: false,
        placeholder: 'Informe detalhes úteis para a visita...',
        order: 6,
      },
    ],
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'form_baptism',
    tenantId: 'tenant_batista_central',
    name: 'Inscrição para o Batismo nas Águas',
    slug: 'inscricao-batismo',
    description:
      'Ficha de inscrição para a próxima turma de discipulado e batismo público da igreja.',
    status: 'archived',
    fields: [
      {
        id: 'f_bt_1',
        name: 'candidate_name',
        label: 'Nome Completo do Candidato',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        id: 'f_bt_2',
        name: 'email',
        label: 'E-mail',
        type: 'email',
        required: true,
        order: 2,
      },
      {
        id: 'f_bt_3',
        name: 'phone',
        label: 'WhatsApp',
        type: 'tel',
        required: true,
        order: 3,
      },
      {
        id: 'f_bt_4',
        name: 'testimony',
        label: 'Breve relato da sua conversão',
        type: 'textarea',
        required: false,
        placeholder: 'Conte resumidamente como você conheceu a Jesus...',
        order: 4,
      },
    ],
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-20T17:00:00Z',
  },
];
